### PR TITLE
os.system replaced with subprocess module

### PR DESCRIPTION
**Pull request by Madhura-saw**
### Description

Substituted the previous use of `os.system` with `subprocess.run`, and implementing try and except for error handling.

- Relevant Issues : #95 
- Type of change :
  - [ ] New feature
  - [x] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

#### Output
Screenshot 2023-10-03 at 12 15 35 PM

### CODE REVIEW

**Comment by stationeros** [comment]
@Madhura-saw  This looks fine, can we add the ouput of a successful run of install and you should be good to go

**Comment by Madhura-saw** [comment]
> @Madhura-saw This looks fine, can we add the ouput of a successful run of install and you should be good to go
So for this I need to setup Trapheus right? and where do I add the output?

**Comment by stationeros** [comment]
just try step 3 and 4 from here https://github.com/intuit/Trapheus#setup and add the output as part of the PR itself

**Comment by Madhura-saw** [comment]
> just try step 3 and 4 from here https://github.com/intuit/Trapheus#setup and add the output as part of the PR itself

okay

**Comment by Madhura-saw** [comment]
I have added the output, the install file is running

**Review by stationeros — APPROVED** [review]

**Pull request merged**
