### PR TITLE
Add create_snapshot_only task

### LINKED ISSUE #63: Separate create_snapshot from db_restore so latter is not run automatically
Hi, I have an enhancement request for Trapheus
we would like to use Trapheus to create and export a Snapshot from one AWS Environment
transfer the exported snapshot to a target Environment (different account) and then restore the snapshot there

currently task create_snapshot does automatically and always run into the db_restore part.
To achieve what we need there need to be a way to separate create_snapshot task from db_restore, so db_restore not to be run after successful create_snapshot

maybe there are various ways to do that, but the simplest one would to do a small (one liner) modification to template.yaml to the step function 

```
"StartClusterSnapshotExportTask": {
                "Type": "Task",
                "Resource": "${ClusterSnapshotExportLambdaArn}",
                "Next": "ClusterRename",
```

by changing ClusterRename to RestorePipelineComplete

We would like to use the code as is so not to clone your code but would like to see this in there.
Or maybe introduce a task create_shapshot_only Task / action and extend the decision logic to stop the step function after having exported the RDS snapshot to S3?

Please feedback on whether such a modification would be possible.
Regards, Peter

### PR DESCRIPTION
**Pull request by RiyaJohn**
### Description
Fixes #63 
Thanks for contributing this Pull Request. Make sure that you submit this Pull Request against the `master` branch of this repository, add a brief description, and tag the relevant issue(s) and PR(s) below.

- Relevant Issues : #63 
- Relevant PRs : (optional)
- Type of change :
  - [x] New feature
  - [ ] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation
  
If task = create_snapshot_only then
Screenshot 2021-11-15 at 11 31 23 AM
Screenshot 2021-11-15 at 11 32 07 AM

### CODE REVIEW

**Comment by RiyaJohn** [comment]
@namitad Please take a look at this PR, sorry for the delay as I initially took this in a different approach which was not convincing to me at the end.

**Comment by RiyaJohn** [comment]
@namitad It will be great if you could also add the 'hacktoberfest-accepted' label to the PR

**Comment by namitad** [comment]
@RiyaJohn Thank you for contributing this addition to Trapheus. could you add some snapshots in the PR description of the updated pipeline?

**Comment by RiyaJohn** [comment]
> @RiyaJohn Thank you for contributing this addition to Trapheus. could you add some snapshots in the PR description of the updated pipeline?

yes will do

**Comment by RiyaJohn** [comment]
@namitad added to PR description, let me know if its enough

**Comment by RiyaJohn** [comment]
@namitad @despot can you check this

**Pull request merged**
