### PR TITLE
Create Labs initial vision statement

### PR DESCRIPTION
**Pull request by stationeros**
Adding the vision statement for labs.

### Description
Adding the initial vision statement for Trapheus Labs

Thanks for contributing this Pull Request. Make sure that you submit this Pull Request against the `master` branch of this repository, add a brief description, and tag the relevant issue(s) and PR(s) below.

- Relevant Issues : (compulsory)
- Relevant PRs : (optional)
- Type of change :
  - [ ] New feature
  - [ ] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

### CODE REVIEW

**Review by namitad — APPROVED** [review]
essentially i would prefer this to be added once some of the functionality has been added to the repo. but approving since its not part of the main readme.

**Comment by stationeros** [comment]
Not sure I understood , vision statements are inherently meant to be forward looking preferably years into future.

**Comment by namitad** [comment]
yes - just providing another perspective where having a functionality implemented along with this would give end users a better understanding. 
that said, please do go ahead and merge the PR.

**Comment by stationeros** [comment]
@namitad I appreciate your idea of implementing a functionality that outlines our vision. It's an interesting concept, but I believe our vision statement should remain as a guiding principle rather than a functional element.

Implementing a functionality directly tied to our vision might limit our flexibility. Our vision is broad for a reason - it allows us to adapt and evolve as Trapheus grows and changes. If we tie a specific functionality to our vision, we might restrict our ability to pivot or adapt in the future.

Our vision is meant to inspire and motivate.. If we turn it into a  functionality, we risk reducing it to a task or a checkbox, which could diminish its inspirational value

While I understand the appeal of making our vision more tangible, I believe there are other ways to achieve this. For example, we could create specific goals or initiatives that align with our vision, rather than turning the vision itself into a functionality

I totally and whole heartedly appreciate your proactive approach and your desire to make our vision a reality. However, I believe it's important to maintain a distinction between our vision (where we want to go) and our operations (how we get there). This allows us to stay focused on our long-term goals while still being able to adjust our strategies and tactics as needed.

Will merge the PR :)

**Pull request merged**
