### PR TITLE
Parallelise the alert and rollback steps in the state machine

### LINKED ISSUE #30: Parallelise the alert and rollback steps in the state machine
Presently in the state machine, in any failure scenario, there is an email and optional slack alert configured.
Post the alert, a rollback is initiated. 
Therefore in scenarios of failure in the alert mechanisms, the rollback is also blocked.

https://github.com/intuit/Trapheus/blob/master/screenshots/failure_handling.png

Enhance this sequential part of the state machine such that the alert and rollback happens in parallel.

Resources to start off: https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-parallel-state.html

### PR DESCRIPTION
**Pull request by RiyaJohn**
### Description

Thanks for contributing this Pull Request. Make sure that you submit this Pull Request against the `master` branch of this repository, add a brief description, and tag the relevant issue(s) and PR(s) below.

- Relevant Issues : Fixes #30 
- Relevant PRs : (optional)
- Type of change :
  - [x] New feature
  - [ ] Bug fix for existing feature
  - [ ] Code quality improvement
  - [ ] Addition or Improvement of tests
  - [ ] Addition or Improvement of documentation

### CODE REVIEW

**Comment by RiyaJohn** [comment]
@namitad added some case images, raised exceptions to mock failure cases:
image
image

**Comment by RiyaJohn** [comment]
> @RiyaJohn could you add screenshots on the scenario where a restore step fails post that the alert is sent and there is a successful revert of the rename step and then the pipeline is completed?

Oh yes, will add

**Comment by RiyaJohn** [comment]
@namitad Adding screenshot on the scenario where a restore step fails post that the alert is sent and there is a successful revert of the rename step and then the pipeline is completed. But looks like there is a bug in the code, I got the revert step successful only when I changed RestoreException to InstanceRestoreException at https://github.com/intuit/Trapheus/blob/master/src/rename/rename_function.py#L15, because that's how exception will be raised ref. https://github.com/intuit/Trapheus/blob/master/src/restore/restore_function.py#L35. Please look at it, not sure if I am missing anything.
image

**Comment by namitad** [comment]
@RiyaJohn could you add the `RestoreException to InstanceRestoreException` change also as part of this?

**Comment by RiyaJohn** [comment]
> @RiyaJohn could you add the `RestoreException to InstanceRestoreException` change also as part of this?

added it

**Comment by namitad** [comment]
@RiyaJohn thank you for including the exception related changes. 
Could you also add some screenshots of this flow for the cluster specific branch to ensure that for both parts of the pipeline, the enhancement works as expected?

**Comment by RiyaJohn** [comment]
> @RiyaJohn thank you for including the exception related changes.
> Could you also add some screenshots of this flow for the cluster specific branch to ensure that for both parts of the pipeline, the enhancement works as expected?
Here you go:
image
image

**Comment by RiyaJohn** [comment]
@namitad ^^^ just in case you missed my reply

**Review by namitad — APPROVED** [review]

**Review by stationeros — APPROVED** [review]
Thanks @RiyaJohn  for this PR.

**Pull request merged**
